
package nl.quintor.rc.web.soap.klant;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import nl.quintor.rc.web.soap.dto.aanmakengebruiker.AanmakenGebruikerRequest;
import nl.quintor.rc.web.soap.dto.aanmakengebruiker.AanmakenGebruikerResponse;
import nl.quintor.rc.web.soap.dto.ophalenklant.OphalenKlantRequest;
import nl.quintor.rc.web.soap.dto.ophalenklant.OphalenKlantResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KlantWebService", targetNamespace = "http://klant.soap.web.rc.quintor.nl/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    nl.quintor.rc.web.soap.dto.aanmakengebruiker.ObjectFactory.class,
    nl.quintor.rc.web.soap.dto.gebruiker.ObjectFactory.class,
    nl.quintor.rc.web.soap.dto.ophalenklant.ObjectFactory.class
})
public interface KlantWebService {


    /**
     * 
     * @param aanmakenGebruikerRequest
     * @return
     *     returns nl.quintor.rc.web.soap.dto.aanmakengebruiker.AanmakenGebruikerResponse
     * @throws AanmakenGebruikerException
     */
    @WebMethod
    @WebResult(name = "AanmakenGebruikerResponse", targetNamespace = "http://www.quintor.nl/rc/gebruikeraanmaken/1.0", partName = "AanmakenGebruikerResponse")
    public AanmakenGebruikerResponse createGebruiker(
        @WebParam(name = "AanmakenGebruikerRequest", targetNamespace = "http://www.quintor.nl/rc/gebruikeraanmaken/1.0", partName = "AanmakenGebruikerRequest")
        AanmakenGebruikerRequest aanmakenGebruikerRequest)
        throws AanmakenGebruikerException
    ;

    /**
     * 
     * @param ophalenKlantRequest
     * @return
     *     returns nl.quintor.rc.web.soap.dto.ophalenklant.OphalenKlantResponse
     */
    @WebMethod
    @WebResult(name = "OphalenKlantResponse", targetNamespace = "http://www.quintor.nl/rc/ophalenklant/1.0", partName = "OphalenKlantResponse")
    public OphalenKlantResponse getKlantGegevens(
        @WebParam(name = "OphalenKlantRequest", targetNamespace = "http://www.quintor.nl/rc/ophalenklant/1.0", partName = "OphalenKlantRequest")
        OphalenKlantRequest ophalenKlantRequest);

}
